/**
 * Draws the app's icons.
 *
 *   npm run icons        # write any icon that has no file yet, then the map
 *   npm run icons -- --sheet   # …and a contact sheet to look at them on
 *
 * Every item in every theme has a silhouette of its own, as an SVG in
 * `assets/icons`. The files are the artwork: edit one in any vector editor, or
 * replace it outright, and it survives — this script never overwrites a file
 * that already exists. It only draws what is missing and then rebuilds
 * `src/ui/icons.generated.ts` from whatever the files on disk say.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { draw } from './icons/draw.mjs';
import { REGISTRY } from './icons/registry.mjs';

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const ICON_DIR = join(ROOT, 'assets', 'icons');
const MAP_FILE = join(ROOT, 'src', 'ui', 'icons.generated.ts');

const SVG = (path) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="currentColor">\n  <path d="${path}" />\n</svg>\n`;

async function write() {
  let drawn = 0;
  let kept = 0;
  for (const [theme, categories] of Object.entries(REGISTRY)) {
    for (const [category, items] of Object.entries(categories)) {
      for (const [id, shapes] of Object.entries(items)) {
        // The registry is keyed by the item's **id**, which is what the app
        // builds an icon's name from — see `iconName` in src/data/themes.ts. It
        // used to be keyed by the label, which worked only for as long as every
        // label happened to slug down to its own id: rename a person and the
        // next run would quietly draw them a second icon under a new name and
        // leave the old file behind as an orphan, with the app still asking for
        // the orphan.
        //
        // A theme's own mark has no item behind it, so it is simply theme.svg.
        const name = category === 'theme' ? 'theme' : `${category}-${id}`;
        const file = join(ICON_DIR, theme, `${name}.svg`);
        if (existsSync(file)) {
          kept++;
          continue;
        }
        await mkdir(dirname(file), { recursive: true });
        await writeFile(file, SVG(draw(shapes)));
        drawn++;
      }
    }
  }
  return { drawn, kept };
}

/** Reads every icon back off disk, so hand-edited files are what ships. */
async function collect() {
  const icons = {};
  const folders = existsSync(ICON_DIR) ? await readdir(ICON_DIR, { withFileTypes: true }) : [];
  for (const folder of folders.filter((entry) => entry.isDirectory())) {
    for (const file of (await readdir(join(ICON_DIR, folder.name))).sort()) {
      if (!file.endsWith('.svg')) continue;
      const svg = await readFile(join(ICON_DIR, folder.name, file), 'utf8');
      const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((match) => match[1]);
      if (paths.length === 0) throw new Error(`${folder.name}/${file} has no path in it`);
      icons[`${folder.name}/${file.replace(/\.svg$/, '')}`] = paths.join('');
    }
  }
  return icons;
}

const HEADER = `/**
 * The icons, as path data, built from the SVG files in assets/icons.
 *
 * Generated by \`npm run icons\` — do not edit this file. Edit the SVG the path
 * came from and run it again; it reads the files rather than redrawing them.
 */

/** Every shape is drawn in a 100 × 100 box. */
export const ICON_BOX = 100;

export const ICONS: Record<string, string> = `;

async function main() {
  const { drawn, kept } = await write();
  const icons = await collect();
  const entries = Object.entries(icons)
    .map(([name, path]) => `  '${name}': '${path}',`)
    .join('\n');
  await writeFile(MAP_FILE, `${HEADER}{\n${entries}\n};\n`);

  console.log(`  ✓ ${drawn} drawn, ${kept} already had a file`);
  console.log(`  ✓ ${Object.keys(icons).length} icons in src/ui/icons.generated.ts`);

  if (process.argv.includes('--sheet')) {
    const cells = Object.entries(icons)
      .map(
        ([name, path]) =>
          `<figure><svg viewBox="0 0 100 100"><path d="${path}"/></svg><figcaption>${name}</figcaption></figure>`,
      )
      .join('\n');
    const sheet = `<!doctype html><meta charset="utf-8"><style>
      body { font: 11px/1.3 system-ui, sans-serif; background: #F6F3EC; color: #26221B; margin: 24px; }
      main { display: grid; grid-template-columns: repeat(10, 1fr); gap: 16px 8px; }
      figure { margin: 0; text-align: center; }
      svg { width: 54px; height: 54px; fill: #26221B; background: #fff; border: 1px solid #E4DFD4; }
      figcaption { margin-top: 4px; color: #6B6455; word-break: break-all; }
    </style><main>${cells}</main>`;
    await writeFile(join(ROOT, 'docs', 'icons.html'), sheet);
    console.log('  ✓ contact sheet at docs/icons.html');
  }
}

await main();
