#!/usr/bin/env node
/**
 * Reads the language file and writes the module the app imports.
 *
 * Metro cannot import YAML, and a parser in the bundle would be a parser
 * shipped to every phone to read a file that never changes at runtime. So the
 * YAML is the source and `src/i18n/strings.generated.ts` is the build of it —
 * the same arrangement the icons use, and committed for the same reason: what
 * ships is checked in, and a test fails if the two drift apart.
 *
 *   npm run locale
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const LOCALE_FILE = join(ROOT, 'locales', 'en-GB.yaml');
export const OUT_FILE = join(ROOT, 'src', 'i18n', 'strings.generated.ts');

/** Every leaf path of the tree, dotted, so the keys can be typed. */
function leafKeys(node, prefix = '') {
  if (typeof node === 'string') return [prefix];
  if (Array.isArray(node)) return [];
  return Object.entries(node).flatMap(([key, value]) =>
    leafKeys(value, prefix ? `${prefix}.${key}` : key),
  );
}

/** TypeScript source for a value, indented to sit inside the object. */
function render(node, depth) {
  const pad = '  '.repeat(depth);
  const inner = '  '.repeat(depth + 1);
  if (typeof node === 'string') return JSON.stringify(node);
  if (Array.isArray(node)) {
    if (node.length === 0) return '[]';
    return `[\n${node.map((item) => `${inner}${render(item, depth + 1)},`).join('\n')}\n${pad}]`;
  }
  const entries = Object.entries(node).map(
    ([key, value]) => `${inner}${JSON.stringify(key)}: ${render(value, depth + 1)},`,
  );
  return `{\n${entries.join('\n')}\n${pad}}`;
}

export async function buildLocale() {
  const source = await readFile(LOCALE_FILE, 'utf8');
  const tree = parse(source);
  const keys = leafKeys(tree).sort();

  return `// Generated by scripts/locale.mjs from locales/en-GB.yaml — do not edit.
// Change the wording there and run \`npm run locale\`.

export const LOCALE = 'en-GB';

export const STRINGS = ${render(tree, 0)} as const;

/** Every plain-string key in the language file, dotted. */
export type StringKey =
${keys.map((key) => `  | ${JSON.stringify(key)}`).join('\n')};
`;
}

const invokedDirectly = process.argv[1] && process.argv[1].endsWith('locale.mjs');
if (invokedDirectly) {
  const built = await buildLocale();
  await writeFile(OUT_FILE, built, 'utf8');
  const count = built.split('\n').filter((line) => line.startsWith('  | ')).length;
  console.log(`${count} strings → src/i18n/strings.generated.ts`);
}
